[project]
name = "photo-email-scheduler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]",
    "pyyaml"
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
